# Generated by Django 4.1.4 on 2022-12-15 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardholder_name', models.CharField(max_length=160)),
                ('number', models.CharField(max_length=19)),
                ('expiry_date', models.CharField(max_length=5)),
                ('CVV', models.CharField(max_length=3)),
                ('card_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.card_type')),
            ],
        ),
    ]
